# ServiceNow Details 
SERVICENOW_USERNAME = " "
SERVICENOW_PASSWORD = " "
SERVICENOW_INSTANCE = " "

# Cisco Webex Details
WEBEX_NOTIFICATION = " "
WEBEX_ACCESS_TOKEN = " "
WEBEX_ALERT_USER = " "
WEBEX_SPACE_NAME = " "
